# Generated by Django 2.2.7 on 2019-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability_Boost_Flaw',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ancestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('hit_points', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], max_length=1, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.CharField(blank=True, max_length=256, null=True)),
                ('pgnum', models.PositiveIntegerField(blank=True, null=True)),
                ('ability_boosts', models.ManyToManyField(blank=True, related_name='Ancestries_Ability_Boosts', to='Ancestries.Ability_Boost_Flaw')),
                ('ability_flaws', models.ManyToManyField(blank=True, related_name='Ancestries_Ability_Flaws', to='Ancestries.Ability_Boost_Flaw')),
                ('heritages', models.ManyToManyField(blank=True, related_name='Ancestries', to='Ancestries.Heritage')),
                ('languages', models.ManyToManyField(blank=True, related_name='Ancestries', to='Ancestries.Language')),
                ('special_abilities', models.ManyToManyField(blank=True, related_name='Ancestries', to='Ancestries.SpecialAbility')),
                ('traits', models.ManyToManyField(blank=True, related_name='Ancestries', to='Ancestries.Trait')),
            ],
        ),
    ]
