# Generated by Django 2.2.7 on 2019-11-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0005_auto_20191030_1742'),
        ('Ancestries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestry',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='Ancestries', to='Feats.Feat'),
        ),
    ]
