# Generated by Django 2.2.7 on 2019-11-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestries', '0003_auto_20191114_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestry',
            name='ability_boosts',
            field=models.ManyToManyField(null=True, related_name='Ancestries_Ability_Boosts', to='Ancestries.Ability_Boost_Flaw'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='ability_flaws',
            field=models.ManyToManyField(null=True, related_name='Ancestries_Ability_Flaws', to='Ancestries.Ability_Boost_Flaw'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='feats',
            field=models.ManyToManyField(null=True, related_name='Ancestries', to='Feats.Feat'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='heritages',
            field=models.ManyToManyField(null=True, related_name='Ancestries', to='Ancestries.Heritage'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='languages',
            field=models.ManyToManyField(null=True, related_name='Ancestries', to='Ancestries.Language'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='special_abilities',
            field=models.ManyToManyField(null=True, related_name='Ancestries', to='Ancestries.SpecialAbility'),
        ),
        migrations.AlterField(
            model_name='ancestry',
            name='traits',
            field=models.ManyToManyField(null=True, related_name='Ancestries', to='Ancestries.Trait'),
        ),
    ]
