# Generated by Django 2.2.7 on 2020-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ancestries', '0006_auto_20200225_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancestry',
            name='free_boosts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
