# Generated by Django 2.2.5 on 2019-10-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feats', '0003_delete_reqskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True)),
                ('skill_name', models.CharField(blank=True, max_length=50)),
                ('proficiency', models.CharField(blank=True, choices=[('T', 'Trained'), ('E', 'Expert'), ('M', 'Master'), ('L', 'Legend')], max_length=1)),
                ('ability_name', models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feats.Feat')),
            ],
        ),
    ]
