# Generated by Django 2.2.7 on 2020-02-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feats', '0007_auto_20191115_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('hit_points', models.IntegerField(blank=True, null=True)),
                ('key_ability', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('N/A', 'NULL')], max_length=3)),
                ('pgnum', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('class_feats', models.ManyToManyField(blank=True, related_name='class_feats', to='Feats.Feat')),
                ('general_feats', models.ManyToManyField(blank=True, related_name='general_feats', to='Feats.Feat')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('proficiency_type', models.CharField(choices=[('CDC', 'Class Dice Check'), ('ARC', 'Armor'), ('PER', 'Perception'), ('SAT', 'Saving Throws'), ('SKS', 'Strike'), ('SKI', 'Skill'), ('WEA', 'Weapon'), ('SDC', 'Spell Dice Check')], max_length=3)),
                ('rank', models.CharField(choices=[('T', 'Trained'), ('E', 'Expert'), ('M', 'Master'), ('L', 'Legendary')], max_length=1)),
                ('key_ability', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('N/A', 'NULL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PathClassFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField()),
                ('pgnum', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('path_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PathClassFeature.path_class+', to='PathClasses.PathClass')),
            ],
        ),
        migrations.CreateModel(
            name='PathClassArchetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('pgnum', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
                ('path_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PathClassArchetype.path_class+', to='PathClasses.PathClass')),
            ],
        ),
        migrations.AddField(
            model_name='pathclass',
            name='proficiencies',
            field=models.ManyToManyField(blank=True, related_name='class_proficiencies', to='PathClasses.Proficiency'),
        ),
        migrations.AddField(
            model_name='pathclass',
            name='skill_feats',
            field=models.ManyToManyField(blank=True, related_name='skill_feats', to='Feats.Feat'),
        ),
    ]
