# Generated by Django 2.2.7 on 2020-02-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PathClasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathclass',
            name='general_feats',
        ),
        migrations.RemoveField(
            model_name='pathclass',
            name='skill_feats',
        ),
    ]
