# Generated by Django 2.2.7 on 2020-02-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PathClasses', '0002_auto_20200225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathclass',
            name='additional_skills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathclassarchetype',
            name='path_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='PathClasses.PathClass'),
        ),
        migrations.AlterField(
            model_name='pathclassfeature',
            name='path_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='PathClasses.PathClass'),
        ),
    ]
