# Generated by Django 2.2.7 on 2019-11-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feats', '0007_auto_20191115_1419'),
        ('Ancestries', '0003_auto_20191114_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('A', 'Action'), ('F', 'Free'), ('R', 'Reaction')], max_length=1)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('trigger', models.TextField(null=True)),
                ('cost', models.IntegerField()),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='Feats.Feat')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='Ancestries.Heritage')),
            ],
        ),
    ]
