# Generated by Django 2.2.7 on 2019-11-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='feat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='Feats.Feat'),
        ),
        migrations.AlterField(
            model_name='action',
            name='heritage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='Ancestries.Heritage'),
        ),
    ]
