# Generated by Django 2.2.5 on 2019-10-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feats', '0002_auto_20191010_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_type', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('ATR', 'Attack Roll'), ('ATD', 'Attack Damage'), ('SPR', 'Spell Roll'), ('SDC', 'Spell DC')], max_length=3)),
                ('mod_value', models.IntegerField()),
                ('feat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiers', to='Feats.Feat')),
            ],
        ),
    ]
