# Generated by Django 2.2.5 on 2019-10-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='feat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='Feats.Feat'),
            preserve_default=False,
        ),
    ]
