# Generated by Django 2.2.7 on 2020-02-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PathClasses', '0001_initial'),
        ('Modifiers', '0002_auto_20191016_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='path_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_features', to='PathClasses.PathClassFeature'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='feat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='Feats.Feat'),
        ),
    ]
