# Generated by Django 2.2.5 on 2019-10-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feats', '0005_auto_20191030_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('feats', models.ManyToManyField(blank=True, related_name='tags', to='Feats.Feat')),
            ],
        ),
    ]
