# Generated by Django 2.2.7 on 2020-03-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ancestries', '0006_auto_20200225_1203'),
        ('PathClasses', '0003_auto_20200226_1305'),
        ('Feats', '0007_auto_20191115_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('playerName', models.CharField(max_length=256)),
                ('hit_poits', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('ancestry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_ancestry', to='Ancestries.Ancestry')),
                ('ancestryFeats', models.ManyToManyField(blank=True, related_name='character_ancestry_feats', to='Feats.Feat')),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_class_archetype', to='PathClasses.PathClassArchetype')),
                ('classFeats', models.ManyToManyField(blank=True, related_name='character_class_feats', to='Feats.Feat')),
                ('generalFeats', models.ManyToManyField(blank=True, related_name='character_general_feats', to='Feats.Feat')),
                ('heritage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_heritage', to='Ancestries.Heritage')),
                ('path_class', models.ManyToManyField(related_name='character_classes', to='PathClasses.PathClass')),
                ('skillFeats', models.ManyToManyField(blank=True, related_name='character_skill_feats', to='Feats.Feat')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_abilities', to='Characters.Character')),
            ],
        ),
    ]
