# Generated by Django 2.2.7 on 2020-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='playerName',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
