# Generated by Django 2.2.7 on 2020-03-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0002_auto_20200308_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='path_class',
            field=models.ManyToManyField(blank=True, related_name='character_classes', to='PathClasses.PathClass'),
        ),
    ]
