# Generated by Django 2.2.7 on 2020-03-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0005_character_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='hit_poits',
            new_name='hit_points',
        ),
    ]
