# Generated by Django 2.2.5 on 2019-09-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_type', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('ATR', 'Attack Roll'), ('ATD', 'Attack Damage'), ('SPR', 'Spell Roll'), ('SDC', 'Spell DC')], max_length=3)),
                ('mod_value', models.IntegerField()),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feats.Feat')),
            ],
        ),
        migrations.CreateModel(
            name='Feat_Skill_Requirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('skill_name', models.CharField(max_length=50)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feats.Feat')),
            ],
        ),
    ]
