# Generated by Django 2.2.5 on 2019-10-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('skill_name', models.CharField(max_length=50)),
                ('feat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='Feats.Feat')),
            ],
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='feat',
        ),
        migrations.DeleteModel(
            name='Feat_Skill_Requirment',
        ),
        migrations.DeleteModel(
            name='Modifier',
        ),
    ]
