# Generated by Django 2.2.5 on 2019-10-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0002_auto_20191010_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReqSkill',
        ),
    ]
