# Generated by Django 2.2.5 on 2019-10-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0003_delete_reqskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='book',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='class_name',
            field=models.CharField(blank=True, choices=[('ALCH', 'Alchemist'), ('BARB', 'Barbarian'), ('BARD', 'Bard'), ('CHAM', 'Champion'), ('CLER', 'Cleric'), ('DRUI', 'Druid'), ('FIGH', 'Fighter'), ('MONK', 'Monk'), ('RANG', 'Ranger'), ('ROGU', 'Rogue'), ('SORC', 'Sorcerer'), ('WIZA', 'Wizard')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_type',
            field=models.CharField(blank=True, choices=[('ANC', 'Ancestry'), ('GEN', 'General'), ('SKI', 'Skill'), ('CLA', 'Class')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='pgnum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
