# Generated by Django 2.2.7 on 2019-11-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0005_auto_20191030_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feat',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('proficiency', models.CharField(blank=True, choices=[('T', 'Trained'), ('E', 'Expert'), ('M', 'Master'), ('L', 'Legend')], max_length=1, null=True)),
                ('ability_name', models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], max_length=3, null=True)),
                ('ability_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Feats.Feat')),
            ],
        ),
        migrations.AddField(
            model_name='feat',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='feats', to='Feats.Tag'),
        ),
    ]
