# Generated by Django 2.2.7 on 2019-11-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feats', '0006_auto_20191115_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feat',
            old_name='title',
            new_name='name',
        ),
    ]
